importPath: node_modules # echidna has to be called in the project's root, where the node_module folder is

# format: 'text'
testMode: assertion
allContracts: false # TODO: if true, filter some useless functions from ERC20
stopOnFail: true

testLimit: 2500000
workers: 8

deployer: "0x10000"
sender: 
  - "0x10000" # echidna_caller
  - "0x20000" # recipient
  - "0x30000" 
  - "0x40000" 
  - "0x50000" 
  - "0x60000" 

cryticArgs:
  - "--solc-remaps"
  - "@openzeppelin/contracts=node_modules/@openzeppelin/contracts/"